version: '3.1'
networks:
  app-tier:
    driver: bridge

services:
  rabbit1:
    image: rabbitmq:3.8-management
    container_name: rabbit1
    hostname: rabbit1
    # restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
      - RABBITMQ_DEFAULT_VHOST=default
    networks:
      - app-tier
